name: Daily Commit

on:
  schedule:
    - cron: '0 18 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Timestamp
        run: |
          echo "Last updated: $(date)" > activity-log.txt

      - name: Commit Changes
        run: |
          git config --global user.name "DebeshPanda555"
          git config --global user.email "itsdkp555@gmail.com"
          git add .
          git commit -m "chore: daily activity update" || echo "No changes to commit"

      - name: Push Changes
        run: git push
